exports.globalLexicon = {
    "let" : { "tk": 0x12, "cls": "keyword" },
    "if" : { "tk": 0x05, "cls": "keyword" },
    "then" : { "tk": 0x06, "cls": "keyword" },
    "else" : { "tk": 0x07, "cls": "keyword" },
    "case" : { "tk": 0x0F, "cls": "keyword" },
    "of" : { "tk": 0x10, "cls": "keyword" },
    "end" : { "tk": 0x11, "cls": "keyword", "length": 0 },
    "true" : { "tk": 0x14, "cls": "val", "length": 0 },
    "false" : { "tk": 0x14, "cls": "val", "length": 0 },
    "add" : { "tk": 0x01, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },    
    "style" : { "tk": 0x01, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
    "width" : { "tk": 0x01, "name": "WIDTH", "cls": "function", "length": 2, "arity": 2},
    "height" : { "tk": 0x01, "name": "HEIGHT", "cls": "function", "length": 2, "arity": 2},
    "scale" : { "tk": 0x01, "name": "SCALE", "cls": "function", "length": 2, "arity": 2},
    "parallels" : { "tk": 0x01, "name": "PARALLELS", "cls": "function", "length": 3, "arity": 3},
    "fill" : { "tk": 0x01, "name": "FILL", "cls": "function", "length": 2, "arity": 2},
    "border-color" : { "tk": 0x01, "name": "BORDER", "cls": "function", "length": 2, "arity": 2},
    "background" : { "tk": 0x01, "name": "BACKGROUND", "cls": "function", "length": 2, "arity": 2},
    "fill-opacity" : { "tk": 0x01, "name": "OPACITY", "cls": "function", "length": 2, "arity": 2},
    "rgb" : { "tk": 0x01, "name": "RGB", "cls": "function", "length": 3, "arity": 3},
    "rgba" : { "tk": 0x01, "name": "RGBA", "cls": "function", "length": 4, "arity": 4},
    "brewer" : { "tk": 0x01, "name": "BREWER", "cls": "function", "length": 1, "arity": 1},    
    "map" : { "tk": 0x01, "name": "MAP", "cls": "function", "length": 3, "arity": 3},
    "states" : { "tk": 0x01, "name": "STATES", "cls": "function", "length": 1, "arity": 1},
    "limit" : { "tk": 0x01, "name": "LIMIT", "cls": "function", "length": 3, "arity": 3},
    "zoom" : { "tk": 0x01, "name": "ZOOM", "cls": "function", "length": 3, "arity": 3},
}
